version: '3.7'
services:
  polido-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INFURA_API_KEY=${INFURA_API_KEY:-0}
        - SUPPORTED_CHAINS=${SUPPORTED_CHAINS:-5}
        - DEFAULT_CHAIN=${DEFAULT_CHAIN:-5}
    image: polido-frontend:latest
    container_name: polido-frontend
    ports:
      - 127.0.0.1:3100:3000
    restart: always
