version: '3.7'
services:
  polido-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: polido-frontend-d:latest
    container_name: PoLido-frontend
    ports:
      - 127.0.0.1:3101:3000
    restart: always
